steps:
- name: 'python:3.10'
  args:
  - pip
  - install
  - firebase-admin
  - --user
- name: 'python:3.10'
  args:
  - python
  - upload_commands.py
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - actions-zapier
  - --gen2
  - --region=europe-west1
  - --source=./actions_zapier
  - --trigger-http
  - --runtime=python310
  - --entry-point=actions_zapier
  - --service-account=command-processor-cf@yggdrasil-ai-hermod.iam.gserviceaccount.com
  - --set-env-vars=PROJECT_ID=$PROJECT_ID,EVENT_BUS=$_EVENT_BUS,EMAIL_ZAP_URL=$_EMAIL_ZAP_URL
  - --project=$PROJECT_ID